-- Table for exam requests (pedidos de exames) generated by the doctor.
create table public.exam_requests (
  id uuid primary key default gen_random_uuid(),
  profile_id uuid not null references public.profiles(id) on delete cascade,
  patient_id uuid null references public.patients(id) on delete set null,
  case_id uuid null references public.cases(id) on delete set null,
  payload jsonb not null default '{}'::jsonb,
  location_state text null,
  issued_at date not null,
  pdf_storage_path text null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index idx_exam_requests_profile_id on public.exam_requests (profile_id);
create index idx_exam_requests_issued_at on public.exam_requests (issued_at desc);

comment on table public.exam_requests is
  'Pedidos de exames gerados pelo perfil. payload contém patientName, birthDate, exams (array de strings resolvidas), hypothesis e observations; pdf_storage_path opcional para PDF no storage.';

create or replace function public.set_updated_at_exam_requests()
returns trigger
language plpgsql
as $$
begin
  new.updated_at := now();
  return new;
end;
$$;

create trigger trg_exam_requests_set_updated_at
  before update on public.exam_requests
  for each row
  execute function public.set_updated_at_exam_requests();
