-- Table for referrals (encaminhamentos) generated by the doctor.
create table public.referrals (
  id uuid primary key default gen_random_uuid(),
  profile_id uuid not null references public.profiles(id) on delete cascade,
  patient_id uuid null references public.patients(id) on delete set null,
  case_id uuid null references public.cases(id) on delete set null,
  payload jsonb not null default '{}'::jsonb,
  location_state text null,
  issued_at date not null,
  pdf_storage_path text null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index idx_referrals_profile_id on public.referrals (profile_id);
create index idx_referrals_issued_at on public.referrals (issued_at desc);

comment on table public.referrals is
  'Encaminhamentos gerados pelo perfil. payload contém patientName, birthDate, specialty, reason, clinicalSummary e urgency; pdf_storage_path opcional para PDF no storage.';

create or replace function public.set_updated_at_referrals()
returns trigger
language plpgsql
as $$
begin
  new.updated_at := now();
  return new;
end;
$$;

create trigger trg_referrals_set_updated_at
  before update on public.referrals
  for each row
  execute function public.set_updated_at_referrals();
