-- Enum for medical certificate type (atestados).
create type public.medical_certificate_type as enum (
  'comparecimento',
  'aptidao_fisica',
  'medico',
  'acompanhante'
);

comment on type public.medical_certificate_type is
  'Tipo do atestado: comparecimento, aptidão física, médico (afastamento), acompanhante.';

-- Table for medical certificates (atestados) generated by the doctor.
create table public.medical_certificates (
  id uuid primary key default gen_random_uuid(),
  profile_id uuid not null references public.profiles(id) on delete cascade,
  type public.medical_certificate_type not null,
  patient_id uuid null references public.patients(id) on delete set null,
  case_id uuid null references public.cases(id) on delete set null,
  payload jsonb not null default '{}'::jsonb,
  location_state text null,
  issued_at date not null,
  pdf_storage_path text null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index idx_medical_certificates_profile_id on public.medical_certificates (profile_id);
create index idx_medical_certificates_issued_at on public.medical_certificates (issued_at desc);

comment on table public.medical_certificates is
  'Atestados médicos gerados pelo perfil. payload contém os dados do formulário por tipo; pdf_storage_path opcional para PDF no storage.';

-- Trigger to keep updated_at in sync (reuse set_updated_at if it exists and works for any table).
create or replace function public.set_updated_at_medical_certificates()
returns trigger
language plpgsql
as $$
begin
  new.updated_at := now();
  return new;
end;
$$;

create trigger trg_medical_certificates_set_updated_at
  before update on public.medical_certificates
  for each row
  execute function public.set_updated_at_medical_certificates();
