-- Table for medical reports (relatórios médicos de corpo livre) generated by the doctor.
create table public.medical_reports (
  id uuid primary key default gen_random_uuid(),
  profile_id uuid not null references public.profiles(id) on delete cascade,
  patient_id uuid null references public.patients(id) on delete set null,
  case_id uuid null references public.cases(id) on delete set null,
  payload jsonb not null default '{}'::jsonb,
  location_state text null,
  issued_at date not null,
  pdf_storage_path text null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index idx_medical_reports_profile_id on public.medical_reports (profile_id);
create index idx_medical_reports_issued_at on public.medical_reports (issued_at desc);

comment on table public.medical_reports is
  'Relatórios médicos de corpo livre gerados pelo perfil. payload contém patientName, birthDate, title e bodyHtml (corpo rich-text); pdf_storage_path opcional para PDF no storage.';

create or replace function public.set_updated_at_medical_reports()
returns trigger
language plpgsql
as $$
begin
  new.updated_at := now();
  return new;
end;
$$;

create trigger trg_medical_reports_set_updated_at
  before update on public.medical_reports
  for each row
  execute function public.set_updated_at_medical_reports();
